version: '3.8'

services:
  post-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "50055:50055"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongodb:27017/post-service
      - KAFKA_BROKERS=kafka:9092
      - AUTH_SERVICE_URL=grpc://auth-service:50051
      - USER_SERVICE_URL=grpc://user-service:50052
      - MEDIA_SERVICE_URL=grpc://media-service:50053
      - INTERACTION_SERVICE_URL=grpc://interaction-service:50054
    volumes:
      - ./logs:/app/logs
      - ./src:/app/src
    depends_on:
      - mongodb
      - kafka
      - zookeeper

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

volumes:
  mongodb_data: 